name: Audit

on:
  push:
  schedule:
    - cron: "37 7 * * *"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: "16"
      - run: npm run audit
